### ISSUE TITLE
Does this work with PixiJS 6.0.2?

### ISSUE THREAD

**Issue by designspin** [endel/pixi-virtual-joystick#5]
Thanks for taking the time to produce this touch joystick, a real time saver for me. I've installed this on my PixiJS project running version 6.0.2. It appears the stick does not move although the events still fire correctly with the data I need. This could well be down to my implementation rather than an error, have you tried this with later PixiJS versions?

**Comment by endel** [comment]
Hi @designspin, glad this has been useful for you! I've just upgraded the peerDependency of this project to allow any version of PIXI. Also just tested with Pixi v6 and the results are the same as with Pixi v5 (only had a few typescript compilation errors which I believe wouldn't impact the actual functionality)

Let me know if you have any issues with it! Cheers!
